name: Test

on:
  - push
  - pull_request

jobs:
  test-code:
    name: Test code
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install -y automake libpcap-dev

      - name: Build software
        run: |
          ./autogen.sh
          ./configure
          make
